In [1]:
import numpy as np

In [3]:
n=np.array([ [1,2,3],[4,5,6],[7,8,9] ])

In [4]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
n.shape

(3, 3)

In [6]:
n[2,1:3]

array([8, 9])

In [7]:
n[0,0:2]

array([1, 2])

In [ ]:
#syntax = n[row,column]

In [8]:
n[1:,2:]

array([[6],
       [9]])

In [9]:
n[1:3,2:3]

array([[6],
       [9]])

In [10]:
n[0:,2:]

array([[3],
       [6],
       [9]])

In [11]:
n[1:2,2:3]

array([[6]])

# arange

In [22]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# reshape

In [20]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.sqrt(81)

9.0

In [24]:
n.max()

9

In [25]:
n.min()

1

In [26]:
n.mean()

5.0

In [27]:
n.argmax()

8

In [28]:
n.argmin()

0

In [29]:
n*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
n/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [31]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# random

In [32]:
np.random.rand(2,2)

array([[0.69201845, 0.70491607],
       [0.13690805, 0.13234037]])

In [33]:
np.random.rand(2)

array([0.81563022, 0.23741193])

In [34]:
np.random.randint(9,90)

52

In [35]:
np.random.randint(9,90,12)

array([14, 64, 39, 59, 27, 43, 88, 46, 43, 83, 45, 22])

In [36]:
np.random.randint(1,9,8)

array([5, 4, 6, 1, 4, 1, 4, 2])

In [43]:
s = np.random.randint(9,90,12).reshape(6,2)

In [42]:
s.sum()

597

In [44]:
s

array([[79, 56],
       [22, 87],
       [29, 67],
       [34, 39],
       [88, 50],
       [33, 30]])

In [45]:
s.sum()

614

In [46]:
s.sum(axis=0)

array([285, 329])

# 3D

In [53]:
d=np.array([ [[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,40],[6,60]] ])

In [54]:
d.shape

(3, 3, 2)

In [55]:
(4,3,4)

(4, 3, 4)

# nan -not a number

In [75]:
x = np.array([12,56,np.nan,66,100,np.nan])

In [76]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [77]:
x.dtype

dtype('float64')